/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package petshop.view;

import DAO.animalDAO;
import beans.Animal;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Luan
 */
public class listarAnimal extends javax.swing.JFrame {
    int id;
    /**
     * Creates new form listarAnimal
     */
    public listarAnimal()
    {   
        initComponents();
        DefaultTableModel tabela = (DefaultTableModel) lanimal.getModel();
        TableColumnModel colunaModelo = lanimal.getColumnModel();
        
        colunaModelo.getColumn(0).setMinWidth(0);
        colunaModelo.getColumn(0).setPreferredWidth(0);
        colunaModelo.getColumn(0).setMaxWidth(0);
        
        preencherTabela();
        
        this.setLocationRelativeTo(null);
    }
    public listarAnimal(int identificador)
    {   
        id=identificador;
        initComponents();
        DefaultTableModel tabela = (DefaultTableModel) lanimal.getModel();
        TableColumnModel colunaModelo = lanimal.getColumnModel();
        
        colunaModelo.getColumn(0).setMinWidth(0);
        colunaModelo.getColumn(0).setPreferredWidth(0);
        colunaModelo.getColumn(0).setMaxWidth(0);
        
        preencherTabela();
        
        this.setLocationRelativeTo(null);
    }
    
    public void preencherTabela() {
        DefaultTableModel tabela = (DefaultTableModel) lanimal.getModel();
        animalDAO adao = new animalDAO();

        for (Animal a : adao.buscarAnimal(id)) {

            tabela.addRow(new Object[]
            {
                a.getId(),  
                a.getTipo(),
                a.getIdade(),
                a.getRaca()
            });

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        voltar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lanimal = new javax.swing.JTable();
        excluirAnimal = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        listarConsulta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        voltar.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        voltar.setText("Voltar pata tela de funções");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        lanimal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tipo", "Idade", "Raça"
            }
        ));
        jScrollPane1.setViewportView(lanimal);

        excluirAnimal.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        excluirAnimal.setText("Excluir animal");
        excluirAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirAnimalActionPerformed(evt);
            }
        });

        back.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        back.setText("Voltar");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton1.setText("Agendar consulta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        listarConsulta.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        listarConsulta.setText("Visualizar consultas");
        listarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarConsultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(back)
                        .addGap(41, 41, 41)
                        .addComponent(listarConsulta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(28, 28, 28)
                        .addComponent(excluirAnimal))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addComponent(voltar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(voltar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(excluirAnimal)
                    .addComponent(back)
                    .addComponent(jButton1)
                    .addComponent(listarConsulta))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        funcoes f= new funcoes();
        f.setVisible(true);
        dispose();
    }//GEN-LAST:event_voltarActionPerformed

    private void excluirAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirAnimalActionPerformed
       if (lanimal.getSelectedRow() == -1) 
        {
            JOptionPane.showMessageDialog(null, "Selecione a linha que deseja excluir");
        } 
        
        else 
        {
            int i =  (int) lanimal.getValueAt(lanimal.getSelectedRow(), 0);
            
            animalDAO adao = new animalDAO();
            adao.deletarAnimal((int) i);
            
            listarCliente lc= new listarCliente();
            lc.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_excluirAnimalActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        listarCliente lc= new listarCliente();
        lc.setVisible(true);
        dispose();
    }//GEN-LAST:event_backActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (lanimal.getSelectedRow() == -1)
        {
            JOptionPane.showMessageDialog(null, "Selecione a linha que deseja agendar");
        }
        else
        {
            int i =  (int) lanimal.getValueAt(lanimal.getSelectedRow(), 0);

            consulta c = new consulta(i);
            c.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void listarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarConsultaActionPerformed
        if (lanimal.getSelectedRow()== -1)
        {
            JOptionPane.showMessageDialog(null, "Selecione o cliente");
        }

        else
        {
            int i =  (int) lanimal.getValueAt(lanimal.getSelectedRow(), 0);
            listarConsulta lc= new listarConsulta(i);
            lc.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_listarConsultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(listarAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(listarAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(listarAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(listarAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new listarAnimal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton excluirAnimal;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable lanimal;
    private javax.swing.JButton listarConsulta;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
