/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package petshop.view;

import DAO.clienteDAO;
import DAO.animalDAO;
import beans.Cliente;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Luan
 */
public class listarCliente extends javax.swing.JFrame {

    /**
     * Creates new form listarCliente
     */
    public listarCliente() {
        initComponents();
        DefaultTableModel tabela = (DefaultTableModel) lcliente.getModel();
        TableColumnModel colunaModelo = lcliente.getColumnModel();
        
        colunaModelo.getColumn(0).setMinWidth(0);
        colunaModelo.getColumn(0).setPreferredWidth(0);
        colunaModelo.getColumn(0).setMaxWidth(0);
        
        preencherTabela();
        
        this.setLocationRelativeTo(null);
    }
    
    public void preencherTabela() {
        DefaultTableModel tabela = (DefaultTableModel) lcliente.getModel();
        clienteDAO cdao = new clienteDAO();

        for (Cliente c : cdao.buscarCliente()) {

            tabela.addRow(new Object[]
            {
                c.getId(),  
                c.getNome(),
                c.getEmail(),
                c.getCPF(),
                c.getIdade(),
                c.getTelcel() 
            });

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        funcoes = new javax.swing.JButton();
        editar = new javax.swing.JButton();
        excluir = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        lcliente = new javax.swing.JTable();
        cadastrarAnimal = new javax.swing.JButton();
        visualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        funcoes.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        funcoes.setText("Voltar para tela de funções");
        funcoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funcoesActionPerformed(evt);
            }
        });

        editar.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        editar.setText("Editar cliente");
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });

        excluir.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        excluir.setText("Excluir cliente");
        excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirActionPerformed(evt);
            }
        });

        lcliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Email", "CPF", "Idade", "Telefone celular"
            }
        ));
        jScrollPane3.setViewportView(lcliente);

        cadastrarAnimal.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        cadastrarAnimal.setText("Cadastrar animal do cliente");
        cadastrarAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarAnimalActionPerformed(evt);
            }
        });

        visualizar.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        visualizar.setText("Visualizar animal do cliente");
        visualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(funcoes)
                .addGap(240, 240, 240))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(editar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(excluir))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cadastrarAnimal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 226, Short.MAX_VALUE)
                        .addComponent(visualizar))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(funcoes)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editar)
                    .addComponent(excluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastrarAnimal)
                    .addComponent(visualizar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void funcoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funcoesActionPerformed
        funcoes f= new funcoes();
        f.setVisible(true);
        dispose();
    }//GEN-LAST:event_funcoesActionPerformed

    private void excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirActionPerformed
        if (lcliente.getSelectedRow() == -1)
        {
            JOptionPane.showMessageDialog(null, "Selecione a linha que deseja excluir");
        }

        else
        {
            int i =  (int) lcliente.getValueAt(lcliente.getSelectedRow(), 0);

            clienteDAO cdao = new clienteDAO();
            cdao.deletarCliente((int) i);

            listarCliente lc= new listarCliente();
            lc.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_excluirActionPerformed

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        if (lcliente.getSelectedRow() == -1)
        {
            JOptionPane.showMessageDialog(null, "Selecione a linha que deseja atualizar");
        }
        else
        {
            int i =  (int) lcliente.getValueAt(lcliente.getSelectedRow(), 0);

            editarCliente ec = new editarCliente(i);
            ec.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_editarActionPerformed

    private void cadastrarAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarAnimalActionPerformed
        if (lcliente.getSelectedRow()== -1)
        {
            JOptionPane.showMessageDialog(null, "Selecione o cliente");
        }
        
        else
        {
            int i =  (int) lcliente.getValueAt(lcliente.getSelectedRow(), 0);
            
            cadastrarAnimal ca= new cadastrarAnimal(i);
            ca.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_cadastrarAnimalActionPerformed

    private void visualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizarActionPerformed
        int i =  (int) lcliente.getValueAt(lcliente.getSelectedRow(), 0);
        listarAnimal la= new listarAnimal(i);
        la.setVisible(true);
        dispose();
    }//GEN-LAST:event_visualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(listarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(listarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(listarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(listarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new listarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarAnimal;
    private javax.swing.JButton editar;
    private javax.swing.JButton excluir;
    private javax.swing.JButton funcoes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable lcliente;
    private javax.swing.JButton visualizar;
    // End of variables declaration//GEN-END:variables
}
